config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  def index
    @flats = Flat.all

    @flats = @flats.where('name LIKE ?', "%#{params[:search][:query]}%") if params[:search][:query]
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @flat.update(flat_params)

    redirect_to @flat
  end

  def destroy
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def set_user
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.input :picture_url %>
  <div class="d-flex">
    <%= f.submit class: 'btn btn-primary', class: 'btn btn-primary me-2' %>
    <% if params[:action] == 'new' %>
      <%= link_to 'Cancel', flats_path, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'Cancel', flat_path(@flat), class: 'btn btn-danger' %>
    <% end %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-6 bg-light p-4">
      <h1>Edit Flat</h1>

      <%= render 'flats/form' %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-4 mb-5">
  <h1>All our flats(<%= @flats.count %>)</h1>

  <div class="cards">
    <% @flats.each do |flat| %>
      <div class="shadow-sm m-0">
        <img src="<%= flat.picture_url %>" class="w-100">
        <div class="bg-light p-4">
          <h3><%= flat.name %></h3>
          <p><%= flat.description.first(45) %>...</p>
          <div class="d-flex">
            <div class="d-flex"><p class="me-2"><i class="fa-solid fa-user"></i></p><h5><%= flat.number_of_guests %></h5></div>
            <div class="d-flex ms-4"><p class="me-1"><i class="fa-solid fa-dollar-sign"></i></p><h5><%= flat.price_per_night %></h5></div>
          </div>
        </div>
        <div class="p-4 bg-white m-0 d-flex">
          <%= link_to 'More info', flat, class: 'text-decoration-none' %>
          <%= link_to 'Edit', edit_flat_path(flat), class: 'text-decoration-none text-warning mx-4' %>
          <%= link_to "Remove", flat, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'text-decoration-none text-danger' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-6 bg-light p-4">
      <h1>Add a new Flat</h1>

      <%= render 'flats/form' %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-8">
      <div class="bg-light p-4">
        <h1><%= @flat.name %></h1>
        <h5><%= @flat.address %></h5>
      </div>
      <div class="mt-4 bg-light p-4">
        <h2>A bit more about this flat...</h2>
        <h6><%= @flat.description %></h6>
      </div>
      <div class="mt-4 bg-light p-4">
        <h2>Details</h2>
        <div class="d-flex">
            <div class="d-flex"><p class="me-2"><i class="fa-solid fa-user"></i></p><h5><%= @flat.number_of_guests %></h5></div>
            <div class="d-flex ms-4"><p class="me-1"><i class="fa-solid fa-dollar-sign"></i></p><h5><%= @flat.price_per_night %></h5></div>
          </div>
      </div>
    </div>
    <div class="col-4"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb2068</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="bg-light d-flex justify-content-between p-3">
  <div>
    <%= link_to flats_path, class: 'text-dark text-decoration-none' do %>
      <h3>Simple Airbnb</h3>
    <% end %>
  </div>
  <div class="d-flex">
    <%= simple_form_for :search, url: flats_path, method: :get do |f| %>
      <div class="d-flex">
        <%= f.input_field :query, label: false, class: 'form-control me-2' %>
        <%= f.button :submit, "Search", class: 'btn btn-outline-success' %>
      </div>
    <% end %>
    <%= link_to 'Add flat', new_flat_path, class: 'btn btn-outline-primary ms-3' %>
  </div>
</div>